mysql:
  image: mysql:5.7
  container_name: $MYSQL_CONTAINER
  environment:
    - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    - MYSQL_DATABASE=$MYSQL_DATABASE
    - MYSQL_USER=$MYSQL_USER
    - MYSQL_PASSWORD=$MYSQL_PASSWORD
  ports:
    - "13306:3306"
    # you can set your port according to your need
  volumes:
    - ./mysql_data:/var/lib/mysql
    #create a mysql_data folder in your project where all the mysql databases will be mounted

phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  container_name : mydamin
  ports:
    - "8080:80"
  links:
    - mysql:db


